### ISSUE TITLE
Application menu resizes windows instead of opening in front of windows

### ISSUE THREAD

**Issue by ibigpapa** [dangvd/ksmoothdock#67] opened 2017-09-28 13:41 UTC
When clicking the application menu it pushes any application opened above it upwards to not collide with the menu.  I think it should open over the top of the existing window instead.

### Before Opening
![ksmooth-dock-application-menu-causing-applocation-not-opened](https://user-images.githubusercontent.com/694054/30969669-b6023e8a-a428-11e7-98f1-7a3121e96121.png)

### After opening
![ksmooth-dock-application-menu-causing-applocation-opened](https://user-images.githubusercontent.com/694054/30969683-bdcbe33c-a428-11e7-8704-6c7d9e0b5ebd.png)

**Comment by dangvd** [comment] 2017-09-28 22:25
This is a feature, not a bug :)

From the release notes:
- Automatically showing part of the screen to improve menu readability with translucent effect.

Without this, I'd find it difficult to read the menu -- that's one reason I don't use translucent/transparent Plasma style with Plasma menu.

**Comment by dangvd** [comment] 2018-03-29 04:30
Re-opening. I will make this behaviour configurable (on/off).

**Comment by dangvd** [comment] 2018-03-30 01:34
Released in v5.9 (there's now an option to turn it on/off).

**Closed by dangvd** 2018-03-30 01:34 UTC
Labels: Fixed In Repo, Type: Feature Request
