### ISSUE TITLE
[KDE Plasma 5.10] Autohided dock doesn't unhide at the left side

### ISSUE THREAD

**Issue by kinoegit** [dangvd/ksmoothdock#63] opened 2017-07-12 04:01 UTC
in KDE Plasma 5.10.2/3, single monitor:
When i try ksmoothdock (same with xfce4-panel) autohided at the left border and on the bottom of the monitor, it doesn't show up when cursor should unhide it.
Dock normally shows up on top or right side.

**Comment by dangvd** [comment] 2017-07-17 14:18
As discussed on the Arch Linux forum (https://bbs.archlinux.org/viewtopic.php?id=227530):
- You can reset ksmoothdock config to default setting values (which has autohide off) by deleting $HOME/.ksmoothdock/ksmoothdockrc and restarting ksmoothdock
- This seems to be specific to KDE Plasma 5.10. Unfortunately I am still using KDE Plasma 5.8 so I can't reproduce and fix this yet but I'll do as soon as I can.

**Comment by theosophist123** [comment] 2018-03-25 21:26
Hello,

Just wondering why this is considered low prio, i mean a dock which has troubles opening on one side of the screen should be a high prio issue...anyways, I do have the same problem (plasma 5.12.3).

Considering we're in march 2018, I guess the author had plenty of time to transition to plasma 5.10 at least and had much time to fix this issue.

**Comment by dangvd** [comment] 2018-03-25 23:56
Hi,

A fix is in the FAQs (https://github.com/dangvd/ksmoothdock/wiki/FAQs), I should have posted here earlier:

- Turning off Touch Screen support's edge swipe gesture (introduced in Plasma 5.10) should fix it.

Does it help?

No, I'm still using 5.8 -- Debian stable is still on 5.8, you see.

**Comment by kinoegit** [comment] 2018-03-31 11:02
> 
    Turning off Touch Screen support's edge swipe gesture (introduced in Plasma 5.10) should fix it.
Does it help?<
# Yes! Thanks a lot!

**Closed** 2018-03-31 11:02 UTC
Labels: Priority: Low, Type: Bug
