### ISSUE TITLE
Folders opening in new tab in Dolphin instead of new window

### ISSUE THREAD

**Issue by 2635599** [dangvd/ksmoothdock#108] opened 2019-11-15 14:25 UTC
i just installed the latest ksmooth dock and got it setup the way i like. 1 dock for browsers / email, and 1 dock for a dolphin shortcut and various folders i want quick access to. when i first setup the folders dock when i'd click a folder on it the folder would open in a new dolphin window, which is the behavior i wanted. after all the updates for the beta kubuntu backports that behavior changed. i normally keep one dolphin window open with 3 tabs, and when i click on any one of the folders on the dock it opens in a new dolphin window, but i noticed shortly after all the backport updates when i click any of the folders on the tab they open in a new tab on my main opened tabbed dolphin window. i'm hoping the updates just changed some minor setting i can change back, but honestly haven't seen any such setting in the dolphin settings. thoughts please, thanks.

running kubuntu 19.10 64 bit

**Comment by dangvd** [comment] 2019-11-16 17:33
Hi,

On my systems, Dolphin still opens on a new window so I can't reproduce it.

Usually there are 2 ways to fix it though:
- Either some settings within Dolphin
- Or, some flags when launching Dolphin, e.g. dolphin --new_window

Again I can't confirm as I don't use the same version.

Let me know how it goes.
Cheers,
Viet

**Comment by dangvd** [comment] 2019-12-08 20:06
Closing, as it's a Dolphin issue.

**Comment by dangvd** [comment] 2019-12-30 17:52
So I think the setting is:
From Dolphin:
Control -> Configure Dolphin -> Startup -> Open new folders in tabs
Untick this box if you want to open new folders in new windows instead.

**Closed** 2022-04-19 19:17 UTC
